# Generated by Django 4.2.7 on 2025-12-11 02:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color (hex)')),
            ],
            options={
                'verbose_name': 'Estado de Asistencia',
                'verbose_name_plural': 'Estados de Asistencia',
                'db_table': 'estado_asistencia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Inventario',
                'verbose_name_plural': 'Estados de Inventario',
                'db_table': 'estado_inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'jornada',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad máxima')),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
                'db_table': 'salon',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='api.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='JornadaSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_salones', to='api.jornada', verbose_name='Jornada')),
                ('profesor_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_salones_encargadas', to='api.usuario', verbose_name='Profesor encargado')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_salones', to='api.salon', verbose_name='Salón')),
            ],
            options={
                'verbose_name': 'Jornada-Salón',
                'verbose_name_plural': 'Jornadas-Salones',
                'db_table': 'jornada_salon',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de compra')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='api.categoria', verbose_name='Categoría')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='api.estadoinventario', verbose_name='Estado')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_responsable', to='api.usuario', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato: 12345678-9', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('edad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Edad (años)')),
                ('tutor_nombre', models.CharField(max_length=100, verbose_name='Nombre del tutor')),
                ('tutor_rut', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato: 12345678-9', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT del tutor')),
                ('tutor_telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del tutor')),
                ('tutor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del tutor')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de emergencia')),
                ('observaciones_medicas', models.TextField(blank=True, null=True, verbose_name='Observaciones médicas')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('jornada_salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='api.jornadasalon', verbose_name='Jornada-Salón')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre_apoderado', models.CharField(max_length=100, verbose_name='Nombre del apoderado')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('tipo_evento', models.CharField(choices=[('reunion', 'Reunión'), ('entrevista', 'Entrevista'), ('retiro', 'Retiro anticipado'), ('otro', 'Otro')], default='reunion', max_length=50, verbose_name='Tipo de evento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_apoderados', to='api.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia de Apoderado',
                'verbose_name_plural': 'Asistencias de Apoderados',
                'db_table': 'asistencia_apoderado',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_llegada', models.TimeField(blank=True, null=True, verbose_name='Hora de llegada')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='api.estadoasistencia', verbose_name='Estado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='api.estudiante', verbose_name='Estudiante')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to='api.usuario', verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'ordering': ['-fecha', 'estudiante__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='idx_usuario_email'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuario_rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='idx_usuario_activo'),
        ),
        migrations.AddIndex(
            model_name='jornadasalon',
            index=models.Index(fields=['jornada', 'salon'], name='idx_jornada_salon'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadasalon',
            unique_together={('jornada', 'salon')},
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['codigo'], name='idx_inventario_codigo'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['categoria'], name='idx_inventario_categoria'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['estado'], name='idx_inventario_estado'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['is_active'], name='idx_inventario_activo'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['jornada_salon'], name='idx_estudiante_jornada_salon'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['rut'], name='idx_estudiante_rut'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['is_active'], name='idx_estudiante_activo'),
        ),
        migrations.AddIndex(
            model_name='asistenciaapoderado',
            index=models.Index(fields=['fecha'], name='idx_asist_apod_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistenciaapoderado',
            index=models.Index(fields=['estudiante'], name='idx_asist_apod_estudiante'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha'], name='idx_asistencia_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['estudiante'], name='idx_asistencia_estudiante'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['estado'], name='idx_asistencia_estado'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['-fecha'], name='idx_asistencia_fecha_desc'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante', 'fecha')},
        ),
    ]
