# Generated by Django 4.2.7 on 2025-12-11 02:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251210_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('mes', models.CharField(max_length=7, verbose_name='Mes')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Vencida')], default='pending', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='api.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'cuota',
                'ordering': ['-mes', 'estudiante'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('tipo', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=20, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='api.cuota', verbose_name='Cuota relacionada')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_registradas', to='api.usuario', verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transaccion',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='idx_transaccion_tipo'), models.Index(fields=['fecha'], name='idx_transaccion_fecha'), models.Index(fields=['-fecha'], name='idx_transaccion_fecha_desc'), models.Index(fields=['cuota'], name='idx_transaccion_cuota')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('cantidad_anterior', models.IntegerField(verbose_name='Cantidad anterior')),
                ('cantidad_nueva', models.IntegerField(verbose_name='Cantidad nueva')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='api.inventario', verbose_name='Item')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='api.usuario', verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item'], name='idx_mov_inv_item'), models.Index(fields=['tipo'], name='idx_mov_inv_tipo'), models.Index(fields=['-created_at'], name='idx_mov_inv_fecha')],
            },
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['estudiante'], name='idx_cuota_estudiante'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['mes'], name='idx_cuota_mes'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['estado'], name='idx_cuota_estado'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['fecha_vencimiento'], name='idx_cuota_vencimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('estudiante', 'mes')},
        ),
    ]
