# Generated by Django 4.2.7 on 2025-12-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cuota_transaccion_movimientoinventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último login'),
        ),
    ]
