# Generated by Django 4.2.7 on 2025-12-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_last_login'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='estudiante',
            name='idx_estudiante_rut',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='contacto_emergencia_nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='contacto_emergencia_telefono',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='observaciones_medicas',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='tutor_email',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='tutor_rut',
        ),
    ]
