# Generated by Django 4.2.7 on 2025-12-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_estudiante_idx_estudiante_rut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['-mes', 'estudiante__nombre'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_llegada',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='registrado_por',
        ),
    ]
