# Generated by Django 4.2.7 on 2025-12-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cuota_options_remove_asistencia_hora_llegada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='is_active',
        ),
    ]
