# Generated by Django 4.2.7 on 2025-12-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_asistencia_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciaapoderado',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='asistenciaapoderado',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='asistenciaapoderado',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='asistenciaapoderado',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='asistenciaapoderado',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='asistenciaapoderado',
            name='numero_reunion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de reunión'),
        ),
    ]
