# Generated by Django 4.2.7 on 2025-12-11 20:56

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    """Eliminar registros duplicados antes de agregar la restricción única"""
    AsistenciaApoderado = apps.get_model('api', 'AsistenciaApoderado')
    
    # Encontrar duplicados (mismo estudiante, misma fecha)
    from django.db.models import Count
    duplicates = (
        AsistenciaApoderado.objects
        .values('estudiante', 'fecha')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    # Para cada grupo de duplicados, mantener solo el más reciente (mayor id)
    for dup in duplicates:
        registros = list(
            AsistenciaApoderado.objects
            .filter(estudiante_id=dup['estudiante'], fecha=dup['fecha'])
            .order_by('id')
            .values_list('id', flat=True)
        )
        # Eliminar todos excepto el último
        if len(registros) > 1:
            ids_to_delete = registros[:-1]  # Todos menos el último
            AsistenciaApoderado.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_asistenciaapoderado_deleted_at_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='asistenciaapoderado',
            constraint=models.UniqueConstraint(fields=('estudiante', 'fecha'), name='unique_estudiante_fecha_asistencia_apoderado'),
        ),
    ]
