# Generated by Django 4.2.7 on 2025-12-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_unique_constraint_asistencia_apoderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='api.estadoinventario', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
    ]
