# Generated by Django 4.2.7 on 2025-12-22 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_inventario_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo'),
        ),
    ]
