# Generated by Django 4.2.7 on 2025-12-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inventario_stock_minimo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventario',
            name='idx_inventario_estado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valor_compra',
        ),
    ]
